version: 2.0
defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/node:chakracore-10.6

jobs:
  build_test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run build:prod

  build_dev:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo pip install awscli
      - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile olive-IAM
      - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile olive-IAM
      - run: aws configure set region $DEFAULT_REGION_NAME --profile olive-IAM

workflows:
  version: 2
  build_test_and_build_dev:
    jobs:
      - build_test:
          context: olive
          filters:
            branches:
              only: /^master/

      - build_dev:
          context: olive
          filters:
            branches:
              only: /^dev/

