version: 2.0

executors:
  default_executor:
    working_directory: ~/workspace
    docker:
      - image: node:10.15.3-jessie

jobs:
  testing_build_prod:
    executor: default_executor
    steps:
      - checkout
      - run: npm install
      - run:
          name: lint check
          command: |
            npm run eslint
      - run:
          name: build test
          command: |
            npm run build:prod

  build_dev:
    executor: default_executor
    steps:
    - checkout
    - run: npm install
    - run:
        name: lint check
        command: |
          npm run eslint
    - run:
        name: build test
        command: |
          npm run build:dev

  deploy_dev:
    executor: default_executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install python
          command: |
            sudo apt-get install python
      - run:
          name: install pip
          command: |
            curl -kL https://bootstrap.pypa.io/get-pip.py | python
      - run: sudo pip install awscli
      - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile olive-IAM
      - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile olive-IAM
      - run: aws configure set region $DEFAULT_REGION_NAME --profile olive-IAM
      - run:
          name: deploy to aws s3
          command: |
            aws s3 sync dist s3://olive-gallery.dev/

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - testing_build_prod:
          filters:
            branches:
              only:
                - /^feature/
                - /^master/

      - build_dev:
          filters:
            branches:
              only: /^dev/

      - deploy_dev:
          context: olive
          requires:
            - build_dev
          filters:
            branches:
              only: /^dev/

