version: 2.0

node: &node
  working_directory: ~/workspace
  docker:
    - image: node:10.15.3-jessie

aws: &aws
  working_directory: ~/workspace
  docker:
    - image: circleci/python:3.6.6

jobs:
  build_test:
    <<: *node
    steps:
      - checkout
      - run: npm install
      - run:
          name: lint check
          command: |
            npm run eslint
      - run:
          name: build test
          command: |
            npm run build:prod
      - run:
          name: add permission
          command: |
            chmod -R 777 ~/workspace
      - save_cache:
          key: dist-file-{{ .Branch }}-{{ .Revision }}
          paths:
            - "./dist"

  deploy_dev:
    <<: *aws
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dist-file-{{ .Branch }}-{{ .Revision }}
      - run: sudo pip install awscli
      - run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile olive-IAM
      - run: aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile olive-IAM
      - run: aws configure set region $DEFAULT_REGION_NAME --profile olive-IAM
      - run:
          name: deploy to aws s3
          command: |
            aws s3 sync dist s3://olive-gallery.dev/

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_test:
          context: olive

      - deploy_dev:
          context: olive
          requires:
            - build_test
          filters:
            branches:
              only: /^dev/

